### ISSUE TITLE
staging system for master branch

### ISSUE THREAD

**Issue by johnyb** [Chaotikum/chaotikum-website#7]
The state of the master branch should be easily visible. In order to achieve this, some automated task could run jekyll to compile the page and push the result into `gh-pages` branch, so it can be viewed on http://chaotikum.github.io/chaotikum-website

**Comment by tarleb** [comment]
[github pages support jekyll](https://help.github.com/articles/using-jekyll-with-pages/) out of the box, so we can skip this for now.  This would become relevant again if we decide to use features not supported by gh-pages.
