### ISSUE TITLE
gh-pages branch broken (deploying to somewhere else than document root)

### ISSUE THREAD

**Issue by johnyb** [Chaotikum/chaotikum-website#9]
When depolying the page to somewhere else than the document root, css is not loaded. :( We need a way to find out, if this can be fixed in some way. See [here](http://chaotikum.github.io/chaotikum-website/) for the currently broken version.

**Comment by tarleb** [comment]
Setting `baseurl` in `_config.yml` fixes this. Should we make `gh-pages` our default branch, or do we want to merge the `master` branch manually?

**Comment by johnyb** [comment]
Since #7 is closed, yes, IMHO gh-pages should get the default. (Just wanted to ask for that on #7)

**Comment by tarleb** [comment]
I allowed myself to push the `baseurl` fix while adjusting the default branch.  https://chaotikum.github.io/chaotikum-website/ works now.  Some design experiments are on https://tarleb.github.io/chaotikum-website

Github pages are nice :smiley:

**Comment by johnyb** [comment]
Yep, sweet!
